// -----------------------------------------------------------------------------
// File Name       : TestModel.cpp
// Generated by : XsmpGenerator-1.1.0.202305171205
// -----------------------------------------------------------------------------
/// @file Test/TestModel.cpp

// ----------------------------------------------------------------------------
// ---------------------------- Include Header Files --------------------
// ----------------------------------------------------------------------------

#include "Smp/IPublication.h"
#include "Test/TestModel.h"
#include "Xsmp/Request.h"

namespace Test {
TestModel::TestModel(::Smp::String8 name, ::Smp::String8 description,
        ::Smp::IObject *parent) :
        TestModelGen::TestModelGen(name, description, parent) {
}

TestModel::~TestModel() {
}

void TestModel::DoPublish(::Smp::IPublication *receiver) {
}

void TestModel::DoConfigure(::Smp::Services::ILogger *logger,
        ::Smp::Services::ILinkRegistry *linkRegistry) {
}

void TestModel::DoConnect(::Smp::ISimulator *simulator) {
}

void TestModel::DoDisconnect() {
}

::Smp::Int32 TestModel::addition(::Smp::Int32 a, ::Smp::Int32 b) {
	return a + b;
}
} // namespace Test
