// -----------------------------------------------------------------------------
// File Name      : AnInterface.h
// Generated by : SimSatGenerator-1.1.0.202305111213
// -----------------------------------------------------------------------------
/// @file ns/AnInterface.h

#ifndef NS_ANINTERFACE_H_
#define NS_ANINTERFACE_H_

// Include the generated header file
#include "ns/AnInterfaceGen.h"

// ----------------------------------------------------------------------------
// ------------------------ Types and Interfaces ------------------------
// ----------------------------------------------------------------------------

namespace ns {
class AnInterface: public AnInterfaceGen {
public:
    ~AnInterface() override = default;
};
} // namespace ns

#endif // NS_ANINTERFACE_H_
