// -----------------------------------------------------------------------------
// File Name       : AModel.cpp
// Generated by : XsmpGenerator-1.1.0.202305111230
// -----------------------------------------------------------------------------
/// @file ns/AModel.cpp

// ----------------------------------------------------------------------------
// ---------------------------- Include Header Files --------------------
// ----------------------------------------------------------------------------

#include "Smp/IPublication.h"
#include "Xsmp/EntryPoint.h"
#include "Xsmp/EventSink.h"
#include "ns/AModel.h"

namespace ns {
AModel::AModel(::Smp::String8 name, ::Smp::String8 description,
        ::Smp::IObject *parent) :
        AModelGen::AModelGen(name, description, parent) {
}

AModel::~AModel() {
}

void AModel::DoPublish(::Smp::IPublication *receiver) {
}

void AModel::DoConfigure(::Smp::Services::ILogger *logger,
        ::Smp::Services::ILinkRegistry *linkRegistry) {
}

void AModel::DoConnect(::Smp::ISimulator *simulator) {
}

void AModel::DoDisconnect() {
}

void AModel::_ep() {
    // TODO implement EntryPoint ep
}
void AModel::_voidEventSink(::Smp::IObject *sender) {
    // TODO implement EventSink voidEventSink
}
void AModel::_int32EventSink(::Smp::IObject *sender, ::Smp::Int32 value) {
    // TODO implement EventSink int32EventSink
}
} // namespace ns
