// -----------------------------------------------------------------------------
// File Name       : AnAbstractModel.cpp
// Generated by : SimSatGenerator-1.1.0.202305111213
// -----------------------------------------------------------------------------
/// @file ns/AnAbstractModel.cpp

// ----------------------------------------------------------------------------
// ---------------------------- Include Header Files --------------------
// ----------------------------------------------------------------------------

#include "Smp/IPublication.h"
#include "ns/AnAbstractModel.h"

namespace ns {
AnAbstractModel::AnAbstractModel(::Smp::String8 name,
        ::Smp::String8 description, ::Smp::IComposite *parent,
        ::Smp::ISimulator *simulator) :
        AnAbstractModelGen::AnAbstractModelGen(name, description, parent,
                simulator) {
}

AnAbstractModel::~AnAbstractModel() {
}

void AnAbstractModel::DoPublish(::Smp::IPublication *receiver) {
}

void AnAbstractModel::DoConfigure(::Smp::Services::ILogger *logger,
        ::Smp::Services::ILinkRegistry *linkRegistry) {
}

void AnAbstractModel::DoConnect(::Smp::ISimulator *simulator) {
}

void AnAbstractModel::DoDisconnect() {
}

} // namespace ns
