// -----------------------------------------------------------------------------
// File Name       : AnAbstractClass.cpp
// Generated by : SimSatGenerator-1.1.0.202305111213
// -----------------------------------------------------------------------------
/// @file ns/AnAbstractClass.cpp

// ----------------------------------------------------------------------------
// ---------------------------- Include Header Files --------------------
// ----------------------------------------------------------------------------

#include "ns/AnAbstractClass.h"

namespace ns {
void AnAbstractClass::voidOperation() {
}
::Smp::Bool AnAbstractClass::getter() {
    ::Smp::Bool ret { };
    return ret;
}
void AnAbstractClass::Setter(::Smp::Bool value) {
}
} // namespace ns
